apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rewards-developer-portal
  description: A portal to everything a Rewards developer ever need.
  annotations:
    backstage.io/view-url: https://github.com/rewards-devops/rewards-developer-portal
    github.com/project-slug: rr-peter-chen/backstage
    backstage.io/techdocs-ref: dir:.
    'backstage.io/kubernetes-id': dev-portal
    'backstage.io/kubernetes-namespace': dev-portal-qa
    'backstage.io/kubernetes-label-selector': 'app=backstage, component=backend'
spec:
  type: service
  owner: rewards-devops/platform-fe
  lifecycle: experimental
